### ISSUE TITLE
Problem showing modal to make In App Purchase

### ISSUE THREAD

**Issue by Dubemtopsite** [glassfy/capacitor-plugin-glassfy#10]
![image](https://user-images.githubusercontent.com/31639636/217723314-0ac85cf7-d53a-492d-9ab1-4d526d108467.png)

I get the above error on my console anytime I call the `const transaction = await Glassfy.purchaseSku({ sku: sku });`

Below is my code
![image](https://user-images.githubusercontent.com/31639636/217723596-79b5df50-1737-4edc-ae46-ca9a91cfc975.png)

Expected the IAP modal to show but not showing

Plugin version
"capacitor-plugin-glassfy": "^2.0.6"
"@capacitor/core": "4.3.0"

**Comment by marcopifferi** [comment]
It looks like the SKU is not a valid object.
Could you please share the code you use to get the Sku? 
I should be an object returned by the offering.

**Comment by Dubemtopsite** [comment]
```
const initGlassfySDK = async () => { 
   try { 
     await Glassfy.initialize({ 
       apiKey: "xxxxxxxxx", 
       watcherMode: false, 
     }); 
  
     const product = isPlatformIos.value 
       ? iosProductIDs.value[1] 
       : iosProductIDs.value[0]; 
  
     iosProduct.value = await Glassfy.skuWithId({ identifier: product }); 
     console.log(typeof iosProduct.value); 
     isPageError.value = false; 
   } catch (error: any) { 
     isPageError.value = true; 
     iapError.value.push({ 
       errorFun: "initGlassfySDK", 
       errorMessage: error.message, 
     }); 
     console.log(error.message); 
   }
```

On a normal the sku return a product

**Comment by marcopifferi** [comment]
We normally recommend to use an offering to get a list of sku. You can create one in our dashboard and get the first or the second sku of the offering.

The offering will return the available SKUs while the skuWithId return any sku (for example SKU of a different platform) and your sku may not be available on App Store or Play Store.

Please convert your code to use the offering and have a look at this guide https://docs.glassfy.io/docs/skus-not-returned-to-your-app

**Comment by Dubemtopsite** [comment]
Stil having same issue after using offerings

**Comment by laradevca** [comment]
We are getting the exact same issue on our end! Everything works on Google Play but not on Apple Store!

Here's our code (we use Nuxt) :
 
```javascript
let skuToBuy = ref('')
const offerings = async function () {
  try {
    const allOfferings = await Glassfy.offerings()
    let offering = allOfferings.all.find((o) => {
      console.log('offering: ', o)
      return o.offeringId === 'default'
    })

    console.log('offerings', offering)
    offering.skus.forEach((sku) => {
      console.log('Found sku: ', sku)
      skuToBuy.value = sku
      // sku.extravars
      // sku.product.description;
      // sku.product.price
    })
  } catch (e) {}
}
const subscribe = async function () {
  try {
    console.log('purchase sku:', skuToBuy.value)
    const transaction = await Glassfy.purchaseSku({
      sku: skuToBuy.value,
    })
    console.log('transaction', transaction)
    const permission = transaction.permissions.all.find(
      (p) => p.permissionId === 'access'
    )
    if (permission && permission.isValid) {
      // unlock aFeature
      console.log('all good baby')
    }
  } catch (e) {
    // initialization error
    console.error('Test', e)
  }
}
```

**Comment by Dubemtopsite** [comment]
`const transaction = await Glassfy.purchaseSku({
      sku: toRaw(skuToBuy.value),
    })
`

Wrapping skuToBuy.value inside toRaw() helped me solve my issue

**Comment by Dubemtopsite** [comment]
For those using Vue 
**Instead of this**
`const transaction = await Glassfy.purchaseSku({ sku: sku });`

**Use this**
const transaction = await Glassfy.purchaseSku({ sku: toRaw(sku) });

**Comment by laradevca** [comment]
Ohh thanks ❤️ 🎉  it's working!!
