### ISSUE TITLE
Add support for Capacitor 5.

### ISSUE THREAD

**Issue by woutersteven** [glassfy/capacitor-plugin-glassfy#14]
The beta has been announced and it might have some breaking changes.

- Announcement: https://ionic.io/blog/announcing-capacitor-5-beta
- Changelog: https://github.com/ionic-team/capacitor/releases (currently at 5.0.0-beta3
- Upgrade guide on site: https://capacitorjs.com/docs/next/updating/5-0 (contains changes details also)

**Comment by marcopifferi** [comment]
We will definitly support Capacitor 5 in future (at the moment vs 5 is in Beta and we are just supporting production versions).

**Comment by woutersteven** [comment]
Capacitor 5 was released yesterday: - https://github.com/ionic-team/capacitor/releases.

**Comment by woutersteven** [comment]
This may be useful to you:

- updating plugins to v5 - https://capacitorjs.com/docs/updating/plugins/5-0

Also some automatic upgrade may be possible (i havent' tested it), but from their docs:

From the plugin folder, run npx @capacitor/plugin-migration-v4-to-v5@latest and it will perform all the file changes automatically.
