### ISSUE TITLE
Upgrade Subscription on Android doesn't cancel current subscription

### ISSUE THREAD

**Issue by noeldap93** [glassfy/capacitor-plugin-glassfy#15]
When I use:
`const transaction = await Glassfy.purchaseSku({ sku: newSku, , skuToUpgrade: currentSkuToUpgrade });`
**sku**: a new subscription plan
**skuToUpgrage**: the active subscription

Glassfy creates a new subscription without cancelling the current one. Since I can't use base plans in the play console because I need a product id for each SKU I don't know what to do.

![image](https://user-images.githubusercontent.com/7764105/236342299-291fe99c-b770-4fc6-b7ff-80cd8f47cf19.png)

![image](https://user-images.githubusercontent.com/7764105/236342370-6d19326a-e5ed-43b2-ae39-ef994d401fd5.png)

![image](https://user-images.githubusercontent.com/7764105/236341896-264952b9-6e9f-45b9-b17a-6567d6f0ca63.png)

**Comment by fcurzel** [comment]
Hello, the Android SDK should indeed automatically cancel the previous subscription.
Your code looks fine, I'll be investigating this and keep you posted!

**Comment by noeldap93** [comment]
Sorry it was our fault. 0ur project was created with an old capacitor version. So npm installed the plugin version 1.x

Upgrading to capacitor-plugin-glassfy@2.0.8 fixed the issue.

**Comment by fcurzel** [comment]
Ok, thank you for taking the time to let me know!
