### ISSUE TITLE
Any plan to upgrade to Play Billing Library version 5.0?

### ISSUE THREAD

**Issue by codeone88** [glassfy/capacitor-plugin-glassfy#17]
New apps are rejected because they need  Billing v5

**Comment by simaxme** [comment]
+1

**Comment by JaHollTV** [comment]
+1

**Comment by Noaber** [comment]
Could anyone give an update about the status of this issue ? Getting a warning for an updated app about deprecation.

**Comment by JaHollTV** [comment]
Please work on this issue!

**Comment by marcopifferi** [comment]
We just released the Capacitor 3.2.0 SDK that Support Google Billing 5.0

The current version still require the product to be backward compatible in the Play Store but it is fully compliant with Google requirements.

No changes are required to apps using Glassfy: just link the new SDK.

In the coming weeks we will release a new update that fully support the base plan and the offering from the play store account.
