### ISSUE TITLE
Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.

### ISSUE THREAD

**Issue by philmmoore** [glassfy/capacitor-plugin-glassfy#18]
Issue exists after upgrading to Ionic 7

Not being an Android developer I'm not sure on the best way/approach to fix this.

**Comment by Saqib92** [comment]
same issue after upgrading to Capacitor 5

**Comment by Saqib92** [comment]
@philmmoore update plugin to v3.0.0 and capacitor to v5+ it will work.

**Comment by philmmoore** [comment]
Thanks @Saqib92
