### ISSUE TITLE
Consumable in-app-purchase products showing empty title and descriptions 

### ISSUE THREAD

**Issue by Saqib92** [glassfy/capacitor-plugin-glassfy#22]
Consumable in-app-purchase products showing empty title and descriptions but showing Price and currency code. 
on the other hand my Subscriptions showing complete data and working fine. 

**Note:** My App is in rejected state on app store. is this the issue? or is it related to plugin ??

**Comment by marcopifferi** [comment]
could you please send a snippet of the code you use to display the product ?

**Comment by Saqib92** [comment]
My IAP service:

```
async getOfferings() {
    const offerings = await Glassfy.offerings();
    return offerings.all;
}
```

My Component:

```
async getOffers() {
    let offering = await this.iap.getOfferings();
    this.offerings = offering.filter((e: any) => { return e.offeringId == 'consumable' });
  }
```

**Comment by marcopifferi** [comment]
Can you contact us on intercom ( the blue bubble on bottom right of our website ) ? 
we need to check on your account and I need to have personal information
