### ISSUE TITLE
Capacitor 5 Build Error - Invalid Project Type

### ISSUE THREAD

**Issue by JonahElbaz** [glassfy/capacitor-plugin-glassfy#25]
Just started integrating glassify with an Ionic v7 app and Capacity v5.

As soon as i run: `yarn add capacitor-plugin-glassfy`
I then run `ionic capacitor copy ios` or `ionic capaciitor run ios -l --external` and I get this error:

```
[ERROR] Invalid project type: react-vite (project config: ./ionic.config.json).
        
        Project type must be one of: angular, react, vue, ionic-angular, ionic1, custom

Bad project type: undefined
```

Not really sure what the implication is there. Any help would be appreciated!

**Comment by canu9** [comment]
Hey we are experiencing the very sam problem. I would also appriociate very much if someone with authority would find a solution to this as soon as possible. Thank you.

**Comment by alicilin** [comment]
I am experiencing the same issue. After installing the plugin, the application gives the error above. Could you please resolve this issue?

**Comment by marcopifferi** [comment]
Hello, 
Could you please the steps required to reproduce the issue starting with an empty project ?

**Comment by alicilin** [comment]
İ've solved the issue. When I changed the minSdkVersion in the android/variables.gradle file from 22 to 24, the problem was resolved.

**Comment by alicilin** [comment]
There is no issue during the installation from scratch. However, when it is added to the project later, it gives this error.

**Comment by alicilin** [comment]
I created a new Ionic project from scratch, and the first thing I did was to install the 'capacitor/glassify' plugin. Unfortunately, I am still encountering the same error...

**Comment by lgarbo** [comment]
Can you post all the steps?

The following works as expected:
```
ionic start myapp blank --type=angular --capacitor
cd myapp
npm install capacitor-plugin-glassfy
ionic build
ionic cap add ios
ionic cap copy
ionic cap sync
```

**Comment by alicilin** [comment]
> Can you post all the steps?
> 
> The following works as expected:
> 
> ```
> ionic start myapp blank --type=angular --capacitor
> cd myapp
> npm install capacitor-plugin-glassfy
> ionic build
> ionic cap add ios
> ionic cap copy
> ionic cap sync
> ```

ionic start myApp list --type=vue       ======== ok
cd myApp                                              ====== ok
ionic capacitor add android                 ====== ok
npm install capacitor-plugin-glassfy  ======= ok
ionic capacitor update                         ==== ok
ionic capacitor sync                             ====== ok
ionic cap run android -l --external     ==== failed (Invalid project type: vue-vite (project config: ./ionic.config.json).)

**Comment by lgarbo** [comment]
I followed your steps: to get it works I just updated `minSdkVersion = 24` in `android/variables.gradle`, by default it's 22. 
My env:
```
# ionic -v
7.1.5
# node -v
v18.17.0
# npm -v
10.2.4
```
package.json
```
{
  "name": "myApp",
  "private": true,
  "version": "0.0.1",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vue-tsc && vite build",
    "preview": "vite preview",
    "test:e2e": "cypress run",
    "test:unit": "vitest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@capacitor/android": "5.5.1",
    "@capacitor/app": "5.0.6",
    "@capacitor/core": "5.5.1",
    "@capacitor/haptics": "5.0.6",
    "@capacitor/keyboard": "5.0.6",
    "@capacitor/status-bar": "5.0.6",
    "@ionic/vue": "^7.0.0",
    "@ionic/vue-router": "^7.0.0",
    "capacitor-plugin-glassfy": "^3.3.2",
    "ionicons": "^7.0.0",
    "vue": "^3.3.0",
    "vue-router": "^4.2.0"
  },
  "devDependencies": {
    "@capacitor/cli": "5.5.1",
    "@vitejs/plugin-legacy": "^5.0.0",
    "@vitejs/plugin-vue": "^4.0.0",
    "@vue/eslint-config-typescript": "^12.0.0",
    "@vue/test-utils": "^2.3.0",
    "cypress": "^13.5.0",
    "eslint": "^8.35.0",
    "eslint-plugin-vue": "^9.9.0",
    "jsdom": "^22.1.0",
    "terser": "^5.4.0",
    "typescript": "^5.1.6",
    "vite": "^5.0.0",
    "vitest": "^0.34.6",
    "vue-tsc": "^1.0.24"
  },
  "description": "An Ionic project"
}

```

**Comment by alicilin** [comment]
The minSdkVersion in our project was already set to version 24. However, I resolved the issue. The problem was not with Glassfy, but with @ionic/cli. When I installed @ionic/cli as a development dependency within the project, the issue was resolved.
