### ISSUE TITLE
npm Critical Vulnerabilities

### ISSUE THREAD

**Issue by simonking76** [glassfy/capacitor-plugin-glassfy#28]
I'm using capacitor-plugin-glassfy in an Iconic / Angular mobile app.
v3.3.2

3 critical and 5 high vulnerabilities are reported when I run npm update and are related to this version of the plugin

npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau

npm WARN deprecated vm2@3.9.19: The library contains critical security issues and should not be used for production! The maintenance of the project has been discontinued. Consider migrating your code to isolated-vm.

npm WARN deprecated superagent@5.3.1: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>.

npm audit shows this info

Severity: critical
vm2 Sandbox Escape vulnerability - https://github.com/advisories/GHSA-cchq-frgv-rjh5
vm2 Sandbox Escape vulnerability - https://github.com/advisories/GHSA-g644-9gfx-q4q4
fix available via `npm audit fix --force`
Will install capacitor-plugin-glassfy@1.1.82, which is a breaking change
node_modules/vm2
  degenerator  3.0.0 - 4.0.4
  Depends on vulnerable versions of vm2
  node_modules/degenerator

**Comment by lgarbo** [comment]
Closed with #29
