### ISSUE TITLE
connectCustomSubscriber returns Sku?

### ISSUE THREAD

**Issue by panstromek** [glassfy/capacitor-plugin-glassfy#30]
`connectCustomSubscriber` returns SKU, based on the type definition:

```typescript
    connectCustomSubscriber(options: {
        subscriberId: string;
    }): Promise<GlassfySku>;
```

This seems to be a mistake in types. If not, what Sku does it return, then? Thanks.

**Comment by lgarbo** [comment]
Thanks for reporting. Closed with aa85757
