### ISSUE TITLE
Google Play Billing Library wrong version

### ISSUE THREAD

**Issue by scamps86** [glassfy/capacitor-plugin-glassfy#36]
Hi,

I've received a warning in the Google Play Console stating that the version of Google Play Billing Library should be 6.0.1 (or later).
Is there related with this Glassfy plugin?

_Update your Play Core Maven dependency to an Android 14 compatible version! Your current Play Core library is incompatible with targetSdkVersion 34 (Android 14), which introduces a backwards-incompatible change to broadcast receivers to improve user security. As a reminder, from August 31, Google Play requires all new app releases to target Android 14. Update to the latest Play Core library version dependency to avoid app crashes: https://developer.android.com/guide/playcore#playcore-migration_

Thank you!

**Comment by plduhoux** [comment]
Hi, same issue here, any information on how to solve this would be appreciated

**Comment by joseduacode** [comment]
Same issue here, I cant find info about google billing sdk version in 4.0.0 release, is it prepared to work with 6.0.1?

**Comment by josevavia** [comment]
Same issue here, I cant find info about google billing sdk version in 4.0.0 release, is it prepared to work with 6.0.1?

**Comment by felixhirschfeld** [comment]
Also here for the same issue

**Comment by DavidGomez-dev** [comment]
Here too

**Comment by foerster** [comment]
+1

**Comment by scamps86** [comment]
Finally, it turned out to be my mistake, and you might encounter the same issue. Basically, Google Play allows you to upload app bundles in multiple tracks besides production:

Open testing, closed testing, internal testing...

I had an old bundle uploaded without the Glassfy library, but it was still marked as available for testers. This bundle was causing the issue with the version of the Billing Library.

To remove the problematic bundle, the only solution I found was to upload a current bundle to that track and promote it to production. This way, the availability of the bundle causing the error is eliminated.

I hope this helps you. Best regards!

**Comment by josevavia** [comment]
> Finally, it turned out to be my mistake, and you might encounter the same issue. Basically, Google Play allows you to upload app bundles in multiple tracks besides production:
> 
> Open testing, closed testing, internal testing...
> 
> I had an old bundle uploaded without the Glassfy library, but it was still marked as available for testers. This bundle was causing the issue with the version of the Billing Library.
> 
> To remove the problematic bundle, the only solution I found was to upload a current bundle to that track and promote it to production. This way, the availability of the bundle causing the error is eliminated.
> 
> I hope this helps you. Best regards!

Can you confirm what version of capacitor-plugin-glassfy are you using?

**Comment by scamps86** [comment]
> > Finally, it turned out to be my mistake, and you might encounter the same issue. Basically, Google Play allows you to upload app bundles in multiple tracks besides production:
> > Open testing, closed testing, internal testing...
> > I had an old bundle uploaded without the Glassfy library, but it was still marked as available for testers. This bundle was causing the issue with the version of the Billing Library.
> > To remove the problematic bundle, the only solution I found was to upload a current bundle to that track and promote it to production. This way, the availability of the bundle causing the error is eliminated.
> > I hope this helps you. Best regards!
> 
> Can you confirm what version of capacitor-plugin-glassfy are you using?

The last one: 4.0.0

**Comment by nitzanrh** [comment]
> Finally, it turned out to be my mistake, and you might encounter the same issue. Basically, Google Play allows you to upload app bundles in multiple tracks besides production:
> 
> Open testing, closed testing, internal testing...
> 
> I had an old bundle uploaded without the Glassfy library, but it was still marked as available for testers. This bundle was causing the issue with the version of the Billing Library.
> 
> To remove the problematic bundle, the only solution I found was to upload a current bundle to that track and promote it to production. This way, the availability of the bundle causing the error is eliminated.
> 
> I hope this helps you. Best regards!

I had this issue as well and I can confirm that this solved it. I had an old bundle in my internal testing group - I uploaded a new build to the internal testing group and then promoted it to production =  problem solved. Thanks for this solution!

EDIT: running latest version 4.0.0
