### ISSUE TITLE
Glassfy.initialize fails on android for the Capacitor 4 version (2.0.1)

### ISSUE THREAD

**Issue by anandsathe67** [glassfy/capacitor-plugin-glassfy#4]
I started running into this issue after I upgraded to 2.0.1 
The returned error is "Error: GlassfyError(code=UnknowError, description=Unexpected error, debug=Service Unavailable)
Works fine on iOS. Is this a known problem ?
Android Version: 12.x
My package.json is
```
{
  "name": "app",
  "devDependencies": {
    "@capacitor/cli": "^3.3.2"
  },
  "dependencies": {
    "@capacitor-community/apple-sign-in": "^1.0.1",
    "@capacitor-community/native-audio": "^3.0.4",
    "@capacitor/android": "^4.2.0",
    "@capacitor/core": "^4.2.0",
    "@capacitor/ios": "^4.2.0",
    "@capacitor/splash-screen": "^4.0.1",
    "@capacitor/app": "^4.0.1",
    "@capacitor/network": "^4.0.1",
    "@capacitor/preferences": "^4.0.1",
    "@capacitor/browser": "^4.0.1",
    "@capacitor/clipboard": "^4.0.1",
    "@capacitor/device": "^4.0.1",
    "@capacitor/haptics": "^4.0.1",
    "@capacitor/filesystem": "^4.1.0",
    "@capacitor/push-notifications": "^4.0.1",
    "@capacitor/share": "^4.0.1",
    "capacitor-firebase-auth": "file:../../plugins/capacitor-firebase-auth",
    "jetifier": "^2.0.0",
    "cordova-plugin-x-socialsharing": "^6.0.4",
    "es6-promise-plugin": "^4.2.2",
    "@capacitor-community/firebase-crashlytics": "^1.3.0",
    "capacitor-plugin-glassfy": "^2.0.1"

  },
  "cordova": {
    "plugins": {
    },
    "platforms": [
      "android",
      "ios"
    ]
  }
}
```

**Comment by marcopifferi** [comment]
Do you have the play services installed on the device/emulator you are using ? 
Service unavailable is normally returned when the device could not connect with Google Play billing service.

**Comment by anandsathe67** [comment]
Yes I do. Everything was fine with the 1.18 version. We just upgraded our app to Capacitor 4 and as part of that exercise moved to 2.x of Glassfy as well. That is when we started seeing this issue.

**Comment by marcopifferi** [comment]
We could not reproduce the issue. It seems to work fine here. 
Is it easy for you to build a sample mini app to reproduce the issue and send it to us ?

**Comment by ovz974** [comment]
Same issue for me. Did you find any solutions ?
