### ISSUE TITLE
accountableSkus is declared as an array of string and not an Array of AccountableSku 

### ISSUE THREAD

**Issue by csurbier** [glassfy/capacitor-plugin-glassfy#5]
export interface GlassfyPermission {
    readonly permissionId: string;
    readonly entitlement: GLASSFY_ENTITLEMENT;
    readonly isValid: boolean;
    readonly expireDate: string;
    **readonly accountableSkus: [string];**
}

However in the doc it's mentionned that it's an array  of AccountableSku. 

https://docs.glassfy.io/docs/permissions

With having an array of string, we can't manipulate the object as a JSON.

**Comment by lgarbo** [comment]
Thanks for reporting, fixed in release [2.0.2](https://github.com/glassfy/capacitor-plugin-glassfy/releases/tag/2.0.2)
