### ISSUE TITLE
GlassfyProduct type definition missing 'title'

### ISSUE THREAD

**Issue by sedonaguy** [glassfy/capacitor-plugin-glassfy#7]
It appears that the GlassfySky type definition does not include title:

export interface GlassfyProduct {
    readonly description: string;
    readonly currencyCode: string;
    readonly price: number;
    readonly introductoryPrice: GlassfyProductDiscount;
    readonly discounts: GlassfyProductDiscount[];
}

Actual data returned:

currencyCode: "USD"
description: "Yearly subscription for Unlimited Recordings"
discounts: [] (0)
identifier: "ios_app_unlimited_yearly_subscription_29.95"
introductoryPrice: {currencyCode: "USD", type: "introductory", numberOfPeriods: 1, period: "P1M", price: 0}
price: 25.989999771118164
title: "App Unlimited - Yearly".         <==== This

**Comment by lgarbo** [comment]
Thanks for reporting, we'll fix in the next release

**Comment by marcopifferi** [comment]
This has been fixed in capacitor-plugin-glassfy 2.0.3
