### ISSUE TITLE
Forgotten license?

### ISSUE THREAD

**Issue by c4ffein** [glassfy/capacitor-plugin-glassfy#9]
Hello,

Contrarily to most of your other repos, the MIT license is not provided here, and the README does not include a LICENSE section, so, while there is "Open Source" in the description, it's legally impossible to use that part of the project as the MIT license permits it. I think you just forgot to include it.

Thanks for that project anyway, I had to use another Capacitor plugin that was just terrible before I found this, went through some of your repositories, the code seems so much better engineered.

**Comment by lgarbo** [comment]
Hi, thanks for pointing out, we add the LICENSE file with latest release [2.0.4](https://github.com/glassfy/capacitor-plugin-glassfy/releases/tag/2.0.4).
